version: "3.8"
services:
  frontend:
    container_name: frontend_CTF
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src:ro
      - /app/node_modules
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  phpmyadmin:
    container_name: phpmyadmin_CTF
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql:5.7
    container_name: db_CTF
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    # expose:
    #   - '3306'
    volumes:
      - CTFtasticDB:/var/lib/mysql
volumes:
  CTFtasticDB:
