version: "3.8"
services:
  frontend:
    container_name: frontend_CTF
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src:ro
      - /app/node_modules
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

  backend:
    container_name: backend_CTF
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_CTF:3306/db?enabledTLSProtocols=TLSv1.2
    depends_on:
      - "db"
    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpmyadmin_CTF
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    container_name: mysqldb_CTF
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - CTFtasticDB:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql  
    networks:
      - mynetwork

volumes:
  CTFtasticDB:
networks:
  mynetwork:
