{{- range .Values.challenges }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-{{- $.Values.teamName }}-{{- .chall}}-ing
  labels:
    {{- include "teamchallenges.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://{{- $.Values.host }}:{{$.Values.host.port}}"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range"
      
spec:
  rules:
    - host: {{ $.Values.host }}
      http:
        paths:
          - path: /{{ $.Values.teamHash }}/{{ .challNum }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: team-{{- $.Values.teamName }}-{{- .chall}}-svc
                port:
                  number: 1100{{ .challNum }}
---
{{- end}}