{{- range .Values.challenges }}
apiVersion: v1
kind: Service
metadata:
  name: team-{{- $.Values.teamName }}-{{- .chall}}-svc
  labels:
    {{- include "teamchallenges.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1100{{ .challNum }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    teamName: {{ $.Values.teamName }}
    teamHash: {{ $.Values.teamHash }}
    challenge: {{ .chall }}
---
{{- end}}