apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamchallenges.fullname" . }}
  labels:
    {{- include "teamchallenges.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teamchallenges.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "teamchallenges.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- range .Values.images }}
        - name: {{ . | quote }}
          image: "{{ . }}:latest"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
        {{- end }}