apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ctftastic.fullname" . }}
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: prepare
          image: alpine:3.10
          command:
            - sh
            - -c
            - 'echo "{{.Values.dockerfile}}" | base64 -d > /workspace/Dockerfile'
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      containers:
        - name: buildkit
          image: ctftastic-buildkit
          imagePullPolicy: Never
          command:
            - sh
            - -c
          #  - "sleep 3600"
            - |
             kubectl port-forward $(kubectl get pod | grep kube-registry-v0 | \awk '{print $1;}') 5002:5002 &
             #sleep 7000;
             source buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=/workspace --local dockerfile=/workspace --output type=image,name=localhost:5002/{{.Values.outputImage}}:latest,push=true,registry.insecure={{.Values.insecureRegistry}};
          securityContext:
            privileged: true
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
            - name: registry-vol
              readOnly: true
              mountPath: /certs
      serviceAccountName: operator-superuser-acc
      volumes:
        - name: workspace
          hostPath:
              path: {{ .Values.workspaceHostPath }}
              type: Directory
        - name: registry-vol
          hostPath:
              path: {{.Values.certsHostPath}}
              type: Directory
  backoffLimit: 2