apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctftastic.fullname" . }}-db-svc
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.other.db.type }}
  ports:
    - port: {{ .Values.service.other.db.port }}
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    ctftastic/type: db
