apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctftastic.fullname" . }}-frontend
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ctftastic.selectorLabels" . | nindent 6 }}
      {{- include "ctftastic.coreSelectorLabels" . | nindent 6 }}
      ctftastic/type: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ctftastic.selectorLabels" . | nindent 8 }}
        {{- include "ctftastic.coreSelectorLabels" . | nindent 8 }}
        ctftastic/type: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ctftastic-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.ctftastic.frontend.repository }}:{{ .Values.image.ctftastic.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.ctftastic.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: REACT_APP_BACKEND_ADDRESS
              value: http://ctftastic/api
            - name: WDS_SOCKET_PORT
              value: "0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}