apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctftastic-ingress
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ctftastic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctftastic-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ctftastic-backend-svc
                port:
                  number: 8080
