apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctftastic.fullname" . }}-challs-operator
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ctftastic.selectorLabels" . | nindent 6 }}
      {{- include "ctftastic.coreSelectorLabels" . | nindent 6 }}
      ctftastic/type: challs-operator
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ctftastic.selectorLabels" . | nindent 8 }}
        {{- include "ctftastic.coreSelectorLabels" . | nindent 8 }}
        ctftastic/type: challs-operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ctftastic-challs-operator
          #command:
          #  - sh
          #  - -c
          #  - "sleep 3600"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.ctftastic.challs.repository }}:{{ .Values.image.ctftastic.challs.tag }}"
          imagePullPolicy: {{ .Values.image.ctftastic.challs.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: operator-superuser-acc