apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-superuser-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-superuser
rules:
- apiGroups: ["apps", "networking.k8s.io", '\', '', 'batch']
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-superuser-binding
subjects:
- kind: ServiceAccount
  name: operator-superuser-acc
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator-superuser
  apiGroup: rbac.authorization.k8s.io
---