apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctftastic.fullname" . }}-phpmyadmin-svc
  labels:
    {{- include "ctftastic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.other.phpmyadmin.type }}
  ports:
    - port: {{ .Values.service.other.phpmyadmin.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    ctftastic/type: db
